// Spring Boot 接口路径统一放这里，页面和服务层不要散写 URL 字符串。
export const API_ENDPOINTS = {
  authRegister: "/api/auth/register",
  authLogin: "/api/auth/login",
  authMe: "/api/auth/me",
  authLogout: "/api/auth/logout",
  dashboardOverview: "/api/dashboard/overview",
  dashboardRecommendedTask: "/api/dashboard/recommended-task",
  dashboardStudyPlan: "/api/dashboard/study-plan",
  dashboardWeeklyOverview: "/api/dashboard/weekly-overview",
  dashboardCommunityLearningTrends: "/api/dashboard/community-learning-trends",
  speakingScenarios: "/api/speaking/scenarios",
  speakingScenario: (scenarioId) => `/api/speaking/scenarios/${encodeURIComponent(scenarioId)}`,
  speakingSessions: "/api/speaking/sessions",
  speakingSession: (sessionId) => `/api/speaking/sessions/${encodeURIComponent(sessionId)}`,
  speakingHistory: "/api/speaking/history",
  speakingSessionMessages: (sessionId) => `/api/speaking/sessions/${encodeURIComponent(sessionId)}/messages`,
  vocabularyMemory: "/api/vocabulary/memory",
  vocabularyPracticeProgress: "/api/vocabulary/practice-progress",
  vocabularyPracticeWords: "/api/vocabulary/practice-words",
  vocabularyPracticeRatings: "/api/vocabulary/practice-ratings",
  reviewVocabulary: "/api/vocabulary/review-vocabulary",
  reviewVocabularySubmit: "/api/vocabulary/review",
  vocabularyWordbookWords: "/api/vocabulary/wordbook-words",
  vocabularyWordbookFavorites: "/api/vocabulary/wordbook-favorites",
  vocabularySnapshot: "/api/vocabulary/snapshot",
  grammarNotebookQuestions: "/api/grammar/notebook-questions",
  grammarPracticeResults: "/api/grammar/practice-results",
  grammarPracticeRatings: "/api/grammar/practice-ratings",
  grammarNotebookFavorites: "/api/grammar/notebook-favorites",
  grammarOverview: "/api/grammar/overview",
  grammarPracticeQuestions: "/api/grammar/practice-questions",
  reviewGrammar: "/api/grammar/review-grammar",
  grammarProgress: "/api/grammar/progress",
  grammarTopics: "/api/grammar/topics",
  grammarSnapshot: "/api/grammar/snapshot",
  profileSnapshot: "/api/profile/snapshot",
  profileLearningPlan: "/api/profile/learning-plan",
  profileDailyStatus: "/api/profile/daily-status"
};
